apiVersion: v1
kind: Secret
metadata:
  name: exchange-secrets
  namespace: exchange
type: Opaque
stringData:
  internal_auth.secret: "deployment-acceptance-secret-32-bytes!!"
  role_mapping.json: |
    {
      "admin": "admin",
      "bench-admin": "admin"
    }
