apiVersion: v1
kind: Service
metadata:
  name: exchange
  namespace: exchange
  labels:
    app: exchange
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3030"
    prometheus.io/path: "/metrics/prometheus"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3030
      targetPort: http
      protocol: TCP
  selector:
    app: exchange
