/**
 * News-to-Market Pipeline / 新闻到市场生成流水线
 * 
 * 这是核心的事件驱动预测市场生成器
 * 
 * 流水线: 新闻 → 事件(Event) → 可验证判断(Outcome) → 预测市场(Market)
 * 
 * 三层市场架构:
 * - L1: 短期新闻驱动 (1-30天) - 每日更新
 * - L2: 中期事件 (1-6个月) - 季度级
 * - L3: 长期叙事 (6个月-2年) - 宏观趋势
 */

// ==================== 类型定义 ====================

export type EventType = 
  | 'policy'      // 政策 (tariffs, regulations, executive orders)
  | 'rate'        // 利率决策 (Fed, ECB, BOJ)
  | 'earnings'    // 财报 (quarterly reports)
  | 'tariff'      // 关税 (trade actions)
  | 'legal'       // 法律 (lawsuits, rulings, sanctions)
  | 'geopolitical'// 地缘政治 (conflicts, diplomacy)
  | 'tech'        // 科技 (product launches, AI developments)
  | 'market'      // 市场 (price movements, IPOs)
  | 'election'    // 选举 (voting, polls)
  | 'crypto'      // 加密货币 (regulations, ETFs)

export type MarketTier = 'L1' | 'L2' | 'L3'

export interface ExtractedEvent {
  id: string
  type: EventType
  subject: string           // "Trump", "ECB", "NVIDIA", "China"
  action: string            // "announce", "raise", "ban", "file"
  details: string           // 具体内容
  window: string            // "3d", "7d", "30d", "Q2", "2026"
  windowDays: number        // 数值化的天数
  certainty: number         // 0.0 - 1.0 置信度
  sourceNews: string        // 原始新闻标题
  sourceUrl?: string        // 新闻链接
  extractedAt: Date         // 提取时间
  tier: MarketTier          // L1/L2/L3
}

export interface GeneratedMarket {
  id: string
  tier: MarketTier
  question: string          // 英文问题
  questionZh: string        // 中文问题
  description: string
  descriptionZh: string
  category: string
  yesPrice: number
  noPrice: number
  endDate: string           // YYYY-MM-DD
  volume: number
  participants: number
  sourceEvent: ExtractedEvent
  template: string          // 使用的模板ID
  createdAt: Date
  isAutoGenerated: boolean
}

// ==================== 事件提取规则 ====================

interface ExtractionRule {
  pattern: RegExp
  type: EventType
  subjectExtractor: (match: RegExpMatchArray) => string
  actionExtractor: (match: RegExpMatchArray) => string
  windowDays: number
  tier: MarketTier
  certaintyBoost: number    // 匹配时增加的置信度
}

const EXTRACTION_RULES: ExtractionRule[] = [
  // ===== 政策/关税类 (L1 短期) =====
  {
    pattern: /(?:trump|biden|white house|administration)\s+(?:announce|impose|sign|order|threaten)s?\s+(\d+%?\s*)?(?:tariff|sanction|ban|restriction)/i,
    type: 'tariff',
    subjectExtractor: () => 'Trump Administration',
    actionExtractor: (m) => m[0],
    windowDays: 7,
    tier: 'L1',
    certaintyBoost: 0.3
  },
  {
    pattern: /tariff(?:s)?\s+(?:on|for|against)\s+([\w\s]+?)\s+(?:to\s+)?(?:take\s+effect|start|begin|effective)/i,
    type: 'tariff',
    subjectExtractor: (m) => m[1] || 'Trade Policy',
    actionExtractor: () => 'tariffs take effect',
    windowDays: 14,
    tier: 'L1',
    certaintyBoost: 0.25
  },
  {
    pattern: /executive\s+order\s+(?:on|for|regarding)\s+([\w\s]+)/i,
    type: 'policy',
    subjectExtractor: (m) => m[1] || 'Executive Policy',
    actionExtractor: () => 'executive order signed',
    windowDays: 7,
    tier: 'L1',
    certaintyBoost: 0.2
  },

  // ===== 央行/利率类 (L1-L2) =====
  {
    pattern: /(fed|federal reserve|fomc)\s+(?:may|might|could|expected to|likely to)\s+(raise|cut|hold|pause)/i,
    type: 'rate',
    subjectExtractor: () => 'Federal Reserve',
    actionExtractor: (m) => `${m[2]} rates`,
    windowDays: 45,
    tier: 'L2',
    certaintyBoost: 0.2
  },
  {
    pattern: /(ecb|european central bank)\s+(?:announce|decision|rate)/i,
    type: 'rate',
    subjectExtractor: () => 'ECB',
    actionExtractor: () => 'rate decision',
    windowDays: 30,
    tier: 'L2',
    certaintyBoost: 0.2
  },
  {
    pattern: /interest\s+rate\s+(?:hike|cut|increase|decrease|decision)/i,
    type: 'rate',
    subjectExtractor: () => 'Central Bank',
    actionExtractor: (m) => m[0],
    windowDays: 30,
    tier: 'L2',
    certaintyBoost: 0.15
  },

  // ===== 财报类 (L1) =====
  {
    pattern: /(nvidia|apple|microsoft|google|amazon|meta|tesla)\s+(?:q[1-4]|quarterly|earnings|report)/i,
    type: 'earnings',
    subjectExtractor: (m) => m[1].toUpperCase(),
    actionExtractor: () => 'earnings report',
    windowDays: 7,
    tier: 'L1',
    certaintyBoost: 0.35
  },
  {
    pattern: /earnings\s+(?:beat|miss|surprise|disappoint)/i,
    type: 'earnings',
    subjectExtractor: () => 'Company',
    actionExtractor: (m) => m[0],
    windowDays: 1,
    tier: 'L1',
    certaintyBoost: 0.4
  },

  // ===== 科技/AI类 (L1-L2) =====
  {
    pattern: /(openai|anthropic|google|microsoft|meta)\s+(?:launch|release|announce|unveil)s?\s+([\w\s]+)/i,
    type: 'tech',
    subjectExtractor: (m) => m[1],
    actionExtractor: (m) => `launch ${m[2]}`,
    windowDays: 30,
    tier: 'L1',
    certaintyBoost: 0.2
  },
  {
    pattern: /(?:entity\s+list|export\s+(?:ban|restriction|control))\s+(?:on|for|against)\s+([\w\s]+)/i,
    type: 'tech',
    subjectExtractor: (m) => m[1] || 'Tech Company',
    actionExtractor: () => 'added to entity list',
    windowDays: 30,
    tier: 'L1',
    certaintyBoost: 0.25
  },
  {
    pattern: /ai\s+(?:bubble|crash|winter|regulation|law|bill)/i,
    type: 'tech',
    subjectExtractor: () => 'AI Industry',
    actionExtractor: (m) => m[0],
    windowDays: 180,
    tier: 'L3',
    certaintyBoost: 0.1
  },

  // ===== 加密货币类 (L1-L2) =====
  {
    pattern: /(bitcoin|btc|ethereum|eth)\s+(?:etf|approval|sec)/i,
    type: 'crypto',
    subjectExtractor: (m) => m[1].toUpperCase(),
    actionExtractor: () => 'ETF decision',
    windowDays: 30,
    tier: 'L2',
    certaintyBoost: 0.25
  },
  {
    pattern: /(bitcoin|btc)\s+(?:hit|reach|break|cross)(?:es|s)?\s+\$?([\d,]+k?)/i,
    type: 'crypto',
    subjectExtractor: () => 'Bitcoin',
    actionExtractor: (m) => `reach $${m[2]}`,
    windowDays: 30,
    tier: 'L1',
    certaintyBoost: 0.2
  },

  // ===== 地缘政治类 (L2-L3) =====
  {
    pattern: /(china|russia|ukraine|taiwan|israel|iran)\s+(?:attack|invade|sanction|negotiate|talks|ceasefire)/i,
    type: 'geopolitical',
    subjectExtractor: (m) => m[1],
    actionExtractor: (m) => m[0].replace(m[1], '').trim(),
    windowDays: 90,
    tier: 'L2',
    certaintyBoost: 0.15
  },
  {
    pattern: /(?:war|conflict|invasion|military)\s+(?:escalat|de-escalat|end|resolution)/i,
    type: 'geopolitical',
    subjectExtractor: () => 'Geopolitical',
    actionExtractor: (m) => m[0],
    windowDays: 180,
    tier: 'L3',
    certaintyBoost: 0.1
  },

  // ===== 选举类 (L2) =====
  {
    pattern: /(trump|biden|harris|desantis)\s+(?:win|lead|poll|elect)/i,
    type: 'election',
    subjectExtractor: (m) => m[1],
    actionExtractor: (m) => m[0],
    windowDays: 90,
    tier: 'L2',
    certaintyBoost: 0.2
  },

  // ===== 法律类 (L1-L2) =====
  {
    pattern: /(sec|doj|ftc|eu)\s+(?:sue|charge|fine|investigate|approve|reject)s?\s+([\w\s]+)/i,
    type: 'legal',
    subjectExtractor: (m) => m[1].toUpperCase(),
    actionExtractor: (m) => `${m[0].split(' ')[1]} ${m[2]}`,
    windowDays: 30,
    tier: 'L2',
    certaintyBoost: 0.2
  },

  // ===== 市场类 (L1) =====
  {
    pattern: /(nasdaq|s&p|dow|spy|qqq)\s+(?:hit|reach|break|crash|rally|drop)/i,
    type: 'market',
    subjectExtractor: (m) => m[1].toUpperCase(),
    actionExtractor: (m) => m[0],
    windowDays: 7,
    tier: 'L1',
    certaintyBoost: 0.2
  },
  {
    pattern: /(nvidia|apple|tesla|microsoft)\s+(?:stock|share)?\s*(?:hit|reach|break|fall|rise)s?\s+(?:to\s+)?\$?([\d.]+)/i,
    type: 'market',
    subjectExtractor: (m) => m[1].toUpperCase(),
    actionExtractor: (m) => `reach $${m[2]}`,
    windowDays: 14,
    tier: 'L1',
    certaintyBoost: 0.25
  }
]

// ==================== 市场生成模板 ====================

interface MarketTemplate {
  id: string
  type: EventType
  tier: MarketTier
  questionEn: string        // 支持 {subject}, {action}, {date}, {price}, {threshold} 占位符
  questionZh: string
  descriptionEn: string
  descriptionZh: string
  category: string
  defaultWindow: number     // 默认天数
}

const MARKET_TEMPLATES: MarketTemplate[] = [
  // ===== L1 短期政策/关税 =====
  {
    id: 'tariff_effect',
    type: 'tariff',
    tier: 'L1',
    questionEn: 'Will {subject} tariffs officially take effect by {date}?',
    questionZh: '{subject} 关税会在 {date} 前正式生效吗？',
    descriptionEn: 'Resolves YES if the announced tariffs are officially implemented by the specified date.',
    descriptionZh: '如果宣布的关税在指定日期前正式实施，则解析为 YES。',
    category: 'policy',
    defaultWindow: 7
  },
  {
    id: 'policy_implement',
    type: 'policy',
    tier: 'L1',
    questionEn: 'Will {subject} be officially signed/implemented within {window}?',
    questionZh: '{subject} 会在 {window} 内正式签署/实施吗？',
    descriptionEn: 'Resolves YES if the policy is officially enacted within the timeframe.',
    descriptionZh: '如果政策在时间范围内正式颁布，则解析为 YES。',
    category: 'policy',
    defaultWindow: 14
  },

  // ===== L1 财报 =====
  {
    id: 'earnings_beat',
    type: 'earnings',
    tier: 'L1',
    questionEn: 'Will {subject} beat earnings expectations in their next report?',
    questionZh: '{subject} 下次财报会超预期吗？',
    descriptionEn: 'Resolves YES if reported EPS exceeds analyst consensus.',
    descriptionZh: '如果报告的每股收益超过分析师预期，则解析为 YES。',
    category: 'stocks',
    defaultWindow: 7
  },
  {
    id: 'stock_price_target',
    type: 'earnings',
    tier: 'L1',
    questionEn: 'Will {subject} stock close above ${price} before earnings?',
    questionZh: '{subject} 股票会在财报前收于 ${price} 以上吗？',
    descriptionEn: 'Resolves YES if the stock closes above the target price before the earnings date.',
    descriptionZh: '如果股票在财报日期前收于目标价格之上，则解析为 YES。',
    category: 'stocks',
    defaultWindow: 7
  },

  // ===== L1-L2 利率 =====
  {
    id: 'rate_decision',
    type: 'rate',
    tier: 'L2',
    questionEn: 'Will {subject} {action} at the next meeting?',
    questionZh: '{subject} 下次会议会{action}吗？',
    descriptionEn: 'Resolves based on the official rate decision announcement.',
    descriptionZh: '根据官方利率决定公告解析。',
    category: 'economy',
    defaultWindow: 45
  },
  {
    id: 'rate_magnitude',
    type: 'rate',
    tier: 'L2',
    questionEn: 'Will {subject} raise/cut rates by ≥{threshold}bp at next meeting?',
    questionZh: '{subject} 下次会议会加/降息 ≥{threshold}bp 吗？',
    descriptionEn: 'Resolves YES if the rate change magnitude meets or exceeds the threshold.',
    descriptionZh: '如果利率变化幅度达到或超过阈值，则解析为 YES。',
    category: 'economy',
    defaultWindow: 45
  },

  // ===== L1 科技 =====
  {
    id: 'tech_launch',
    type: 'tech',
    tier: 'L1',
    questionEn: 'Will {subject} {action} within {window}?',
    questionZh: '{subject} 会在 {window} 内{action}吗？',
    descriptionEn: 'Resolves YES if the product/feature is officially launched.',
    descriptionZh: '如果产品/功能正式发布，则解析为 YES。',
    category: 'tech',
    defaultWindow: 30
  },
  {
    id: 'entity_list',
    type: 'tech',
    tier: 'L1',
    questionEn: 'Will {subject} be added to US Entity List within {window}?',
    questionZh: '{subject} 会在 {window} 内被加入美国实体清单吗？',
    descriptionEn: 'Resolves YES if the company is officially added to the Entity List.',
    descriptionZh: '如果公司被正式加入实体清单，则解析为 YES。',
    category: 'tech',
    defaultWindow: 30
  },

  // ===== L1 加密货币 =====
  {
    id: 'crypto_price',
    type: 'crypto',
    tier: 'L1',
    questionEn: 'Will {subject} reach ${price} before {date}?',
    questionZh: '{subject} 会在 {date} 前达到 ${price} 吗？',
    descriptionEn: 'Resolves YES if the cryptocurrency reaches the target price.',
    descriptionZh: '如果加密货币达到目标价格，则解析为 YES。',
    category: 'crypto',
    defaultWindow: 30
  },
  {
    id: 'crypto_etf',
    type: 'crypto',
    tier: 'L2',
    questionEn: 'Will {subject} ETF be approved by {date}?',
    questionZh: '{subject} ETF 会在 {date} 前获批吗？',
    descriptionEn: 'Resolves YES if the ETF receives SEC approval.',
    descriptionZh: '如果 ETF 获得 SEC 批准，则解析为 YES。',
    category: 'crypto',
    defaultWindow: 90
  },

  // ===== L2 地缘政治 =====
  {
    id: 'geopolitical_escalation',
    type: 'geopolitical',
    tier: 'L2',
    questionEn: 'Will {subject} conflict escalate to {threshold} before {date}?',
    questionZh: '{subject} 冲突会在 {date} 前升级到{threshold}吗？',
    descriptionEn: 'Resolves YES if the conflict escalates to the specified level.',
    descriptionZh: '如果冲突升级到指定级别，则解析为 YES。',
    category: 'geopolitics',
    defaultWindow: 90
  },
  {
    id: 'ceasefire',
    type: 'geopolitical',
    tier: 'L2',
    questionEn: 'Will there be a ceasefire in {subject} within {window}?',
    questionZh: '{subject} 会在 {window} 内停火吗？',
    descriptionEn: 'Resolves YES if an official ceasefire is announced and holds.',
    descriptionZh: '如果正式宣布停火并维持，则解析为 YES。',
    category: 'geopolitics',
    defaultWindow: 90
  },

  // ===== L2 选举 =====
  {
    id: 'election_win',
    type: 'election',
    tier: 'L2',
    questionEn: 'Will {subject} win the {action}?',
    questionZh: '{subject} 会赢得{action}吗？',
    descriptionEn: 'Resolves YES based on official election results.',
    descriptionZh: '根据官方选举结果解析。',
    category: 'politics',
    defaultWindow: 90
  },

  // ===== L2 法律 =====
  {
    id: 'legal_ruling',
    type: 'legal',
    tier: 'L2',
    questionEn: 'Will {subject} rule in favor of {action} within {window}?',
    questionZh: '{subject} 会在 {window} 内做出有利于{action}的裁决吗？',
    descriptionEn: 'Resolves YES if the ruling is in favor of the specified party.',
    descriptionZh: '如果裁决有利于指定方，则解析为 YES。',
    category: 'legal',
    defaultWindow: 60
  },

  // ===== L1 市场 =====
  {
    id: 'index_level',
    type: 'market',
    tier: 'L1',
    questionEn: 'Will {subject} close above {price} by {date}?',
    questionZh: '{subject} 会在 {date} 前收于 {price} 以上吗？',
    descriptionEn: 'Resolves YES if the index closes above the target level.',
    descriptionZh: '如果指数收于目标水平之上，则解析为 YES。',
    category: 'stocks',
    defaultWindow: 7
  },

  // ===== L3 长期叙事 =====
  {
    id: 'ai_bubble',
    type: 'tech',
    tier: 'L3',
    questionEn: 'Will AI investment decline by ≥{threshold}% in 2026?',
    questionZh: 'AI 投资会在 2026 年下降 ≥{threshold}% 吗？',
    descriptionEn: 'Resolves YES if reported AI investment figures show the specified decline.',
    descriptionZh: '如果报告的 AI 投资数据显示指定的下降幅度，则解析为 YES。',
    category: 'tech',
    defaultWindow: 365
  },
  {
    id: 'btc_supercycle',
    type: 'crypto',
    tier: 'L3',
    questionEn: 'Will Bitcoin reach ${price} before the next halving cycle crash?',
    questionZh: '比特币会在下一次减半周期崩盘前达到 ${price} 吗？',
    descriptionEn: 'Resolves YES if BTC reaches the target before a major correction.',
    descriptionZh: '如果 BTC 在大幅回调前达到目标，则解析为 YES。',
    category: 'crypto',
    defaultWindow: 365
  }
]

// ==================== 核心流水线类 ====================

export class NewsToMarketPipeline {
  private processedEventIds: Set<string> = new Set()
  private generatedMarkets: GeneratedMarket[] = []
  private lastRunTime: Date | null = null

  /**
   * 从新闻标题提取事件
   */
  extractEvent(newsTitle: string, newsUrl?: string): ExtractedEvent | null {
    // Extract events by matching patterns
    for (const rule of EXTRACTION_RULES) {
      const match = newsTitle.match(rule.pattern)
      if (match) {
        const baseCertainty = 0.5 + rule.certaintyBoost
        const certainty = Math.min(1.0, baseCertainty + (this.calculateNewsCertainty(newsTitle) * 0.2))
        
        const event: ExtractedEvent = {
          id: this.generateEventId(newsTitle, rule.type),
          type: rule.type,
          subject: rule.subjectExtractor(match),
          action: rule.actionExtractor(match),
          details: newsTitle,
          window: this.formatWindow(rule.windowDays),
          windowDays: rule.windowDays,
          certainty,
          sourceNews: newsTitle,
          sourceUrl: newsUrl,
          extractedAt: new Date(),
          tier: rule.tier
        }
        
        return event
      }
    }
    
    return null
  }

  /**
   * 从事件生成预测市场
   */
  generateMarketFromEvent(event: ExtractedEvent): GeneratedMarket | null {
    // 检查是否已处理
    if (this.processedEventIds.has(event.id)) {
      return null
    }

    // 找到匹配的模板
    const template = this.findBestTemplate(event)
    if (!template) {
      return null
    }

    // 计算结束日期
    const endDate = this.calculateEndDate(event)
    
    // 生成问题文本
    const question = this.formatQuestion(template.questionEn, event)
    const questionZh = this.formatQuestion(template.questionZh, event)
    const description = this.formatQuestion(template.descriptionEn, event)
    const descriptionZh = this.formatQuestion(template.descriptionZh, event)

    // 计算初始价格（基于置信度）
    const yesPrice = this.calculateInitialPrice(event)
    
    const market: GeneratedMarket = {
      id: `auto_${event.tier.toLowerCase()}_${Date.now()}_${Math.random().toString(36).substr(2, 6)}`,
      tier: event.tier,
      question,
      questionZh,
      description,
      descriptionZh,
      category: template.category,
      yesPrice,
      noPrice: 1 - yesPrice,
      endDate,
      volume: this.estimateInitialVolume(event),
      participants: this.estimateInitialParticipants(event),
      sourceEvent: event,
      template: template.id,
      createdAt: new Date(),
      isAutoGenerated: true
    }

    // 标记为已处理
    this.processedEventIds.add(event.id)
    this.generatedMarkets.push(market)

    return market
  }

  /**
   * 批量处理新闻列表
   */
  processNewsBatch(newsList: Array<{ title: string; url?: string; date?: string }>): GeneratedMarket[] {
    const markets: GeneratedMarket[] = []
    const now = new Date()
    
    for (const news of newsList) {
      // 只处理最近 72 小时的新闻
      if (news.date) {
        const newsDate = new Date(news.date)
        const hoursDiff = (now.getTime() - newsDate.getTime()) / (1000 * 60 * 60)
        if (hoursDiff > 72) continue
      }

      const event = this.extractEvent(news.title, news.url)
      if (event && event.certainty >= 0.5) {  // 只处理高置信度事件
        const market = this.generateMarketFromEvent(event)
        if (market) {
          markets.push(market)
        }
      }
    }

    this.lastRunTime = now
    return markets
  }

  /**
   * 获取按层级分组的市场
   */
  getMarketsByTier(): { L1: GeneratedMarket[], L2: GeneratedMarket[], L3: GeneratedMarket[] } {
    return {
      L1: this.generatedMarkets.filter(m => m.tier === 'L1'),
      L2: this.generatedMarkets.filter(m => m.tier === 'L2'),
      L3: this.generatedMarkets.filter(m => m.tier === 'L3')
    }
  }

  /**
   * 获取今日生成的市场
   */
  getTodayMarkets(): GeneratedMarket[] {
    const today = new Date()
    today.setHours(0, 0, 0, 0)
    return this.generatedMarkets.filter(m => m.createdAt >= today)
  }

  /**
   * 清除过期市场
   */
  cleanExpiredMarkets(): void {
    const now = new Date()
    this.generatedMarkets = this.generatedMarkets.filter(m => {
      const endDate = new Date(m.endDate)
      return endDate > now
    })
  }

  // ==================== 辅助方法 ====================

  private generateEventId(title: string, type: EventType): string {
    const hash = title.toLowerCase().replace(/[^a-z0-9]/g, '').substring(0, 20)
    return `${type}_${hash}_${Date.now()}`
  }

  private formatWindow(days: number): string {
    if (days <= 7) return `${days}d`
    if (days <= 30) return `${Math.ceil(days / 7)}w`
    if (days <= 90) return `${Math.ceil(days / 30)}m`
    if (days <= 180) return 'Q' + Math.ceil(days / 90)
    return `${Math.ceil(days / 365)}y`
  }

  private calculateNewsCertainty(title: string): number {
    // 根据关键词增加置信度
    let boost = 0
    const lowerTitle = title.toLowerCase()
    
    if (lowerTitle.includes('official') || lowerTitle.includes('confirm')) boost += 0.15
    if (lowerTitle.includes('breaking') || lowerTitle.includes('just in')) boost += 0.1
    if (lowerTitle.includes('announce') || lowerTitle.includes('sign')) boost += 0.1
    if (lowerTitle.includes('may') || lowerTitle.includes('might') || lowerTitle.includes('could')) boost -= 0.1
    if (lowerTitle.includes('rumor') || lowerTitle.includes('speculation')) boost -= 0.2
    
    return Math.max(0, Math.min(0.5, boost))
  }

  private findBestTemplate(event: ExtractedEvent): MarketTemplate | null {
    // 首先按类型和层级匹配
    const matches = MARKET_TEMPLATES.filter(t => t.type === event.type && t.tier === event.tier)
    if (matches.length > 0) {
      return matches[0]
    }
    
    // 其次只按类型匹配
    const typeMatches = MARKET_TEMPLATES.filter(t => t.type === event.type)
    if (typeMatches.length > 0) {
      return typeMatches[0]
    }
    
    return null
  }

  private calculateEndDate(event: ExtractedEvent): string {
    const now = new Date()
    const endDate = new Date(now.getTime() + event.windowDays * 24 * 60 * 60 * 1000)
    return endDate.toISOString().split('T')[0]
  }

  private formatQuestion(template: string, event: ExtractedEvent): string {
    const endDate = this.calculateEndDate(event)
    const formattedDate = new Date(endDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
    
    return template
      .replace(/{subject}/g, event.subject)
      .replace(/{action}/g, event.action)
      .replace(/{date}/g, formattedDate)
      .replace(/{window}/g, event.window)
      .replace(/{price}/g, '100')  // 默认价格
      .replace(/{threshold}/g, '25') // 默认阈值
  }

  private calculateInitialPrice(event: ExtractedEvent): number {
    // 基于置信度设置初始价格
    // 高置信度 = 更接近 0.5（更不确定）
    // 低置信度 = 更极端的价格
    const base = 0.5
    const deviation = (1 - event.certainty) * 0.3
    const randomBias = (Math.random() - 0.5) * 0.2
    
    return Math.max(0.1, Math.min(0.9, base + deviation * (Math.random() > 0.5 ? 1 : -1) + randomBias))
  }

  private estimateInitialVolume(event: ExtractedEvent): number {
    const baseVolume: Record<MarketTier, number> = {
      'L1': 500000,
      'L2': 1000000,
      'L3': 2000000
    }
    const multiplier = 0.5 + Math.random()
    return Math.floor(baseVolume[event.tier] * multiplier * event.certainty)
  }

  private estimateInitialParticipants(event: ExtractedEvent): number {
    const baseParticipants: Record<MarketTier, number> = {
      'L1': 500,
      'L2': 1000,
      'L3': 2000
    }
    const multiplier = 0.5 + Math.random()
    return Math.floor(baseParticipants[event.tier] * multiplier)
  }
}

// ==================== 单例实例 ====================

export const newsToMarketPipeline = new NewsToMarketPipeline()

// ==================== 便捷函数 ====================

/**
 * 快速从单条新闻生成市场
 */
export function generateMarketFromNews(title: string, url?: string): GeneratedMarket | null {
  const event = newsToMarketPipeline.extractEvent(title, url)
  if (event && event.certainty >= 0.5) {
    return newsToMarketPipeline.generateMarketFromEvent(event)
  }
  return null
}

/**
 * 批量处理新闻
 */
export function processNewsBatch(newsList: Array<{ title: string; url?: string; date?: string }>): GeneratedMarket[] {
  return newsToMarketPipeline.processNewsBatch(newsList)
}

/**
 * 获取今日新生成的市场数量
 */
export function getTodayMarketCount(): number {
  return newsToMarketPipeline.getTodayMarkets().length
}

// ==================== 示例新闻测试 ====================

export const SAMPLE_NEWS_FOR_TESTING = [
  { title: "Trump announces 25% tariffs on Canadian goods starting Feb 1", date: "2026-01-23" },
  { title: "Federal Reserve expected to cut rates by 25bp at March meeting", date: "2026-01-23" },
  { title: "NVIDIA Q4 earnings report scheduled for Feb 21", date: "2026-01-23" },
  { title: "ECB to announce rate decision next Thursday", date: "2026-01-22" },
  { title: "OpenAI launches GPT-5 preview to enterprise customers", date: "2026-01-22" },
  { title: "Bitcoin breaks $100,000 for first time in history", date: "2026-01-21" },
  { title: "SEC may approve Ethereum ETF by end of Q1", date: "2026-01-21" },
  { title: "China-Taiwan tensions escalate after naval incident", date: "2026-01-20" },
  { title: "AI chip export ban on SMIC expected within 30 days", date: "2026-01-20" },
  { title: "Apple stock reaches $250 ahead of earnings", date: "2026-01-19" }
]
